### ISSUE TITLE
UnboundLocalError: local variable 'curr_char' referenced before assignment

### ISSUE THREAD

**Issue by drdhaval2785** [tylergneill/skrutable#2]
To overcome the problem in #1, I have commented out three lines in skrutable_one.py which use this timestamp.
The next issue I ran into is as follows.
```bash
dhaval@dhaval-Aspire-5750:~/.local/lib/python3.9/site-packages/skrutable$ python3 skrutable_one.py --identify_meter --whole_file /var/www/html/metre/ARMH_test.txt resplit_option=resplit_lite from_scheme=DEV
Traceback (most recent call last):
  File "/home/dhaval/.local/lib/python3.9/site-packages/skrutable/skrutable_one.py", line 81, in <module>
    result = MI.identify_meter(verse, from_scheme=f_s, resplit_option=r_o)
  File "/home/dhaval/.local/lib/python3.9/site-packages/skrutable/meter_identification.py", line 832, in identify_meter
    V = S.scan(rw_str, from_scheme=from_scheme)
  File "/home/dhaval/.local/lib/python3.9/site-packages/skrutable/scansion.py", line 404, in scan
    V.text_SLP = T.transliterate(V.text_cleaned)
  File "/home/dhaval/.local/lib/python3.9/site-packages/skrutable/transliteration.py", line 173, in transliterate
    self.linear_preprocessing(self.scheme_in, 'SLP')
  File "/home/dhaval/.local/lib/python3.9/site-packages/skrutable/transliteration.py", line 130, in linear_preprocessing
    if curr_char in phonemes.SLP_consonants:
UnboundLocalError: local variable 'curr_char' referenced before assignment
```

**Comment by tylergneill** [comment]
I've made an adjustment, but it would help to know what input generated the problem, so that we can test.

**Comment by tylergneill** [comment]
Closing this absent any further interest
